/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import java.awt.BorderLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import functions.RoundedButton;

/**
 *
 * @author samih
 */

public class AdminPage extends javax.swing.JFrame {

        /**
         * Creates new form ADMIN
         */
        private int clientId;
        private String adminName;
        

        /**
         * Creates new form ADMIN - default constructor
         */
        public AdminPage() {
                this.clientId = 0;
                this.adminName = "Administrator";
                initComponents();
                setSize(1200, 601);
                setLocationRelativeTo(null);
                refreshDashboardStats();

                // Set default admin name
                jLabel20.setText(adminName);
        }

        /**
         * Creates new form ADMIN - with admin name (used by login)
         */
        public AdminPage(int clientId, String adminName) {
                this.clientId = clientId;
                this.adminName = adminName;
                initComponents();
                setSize(1200, 601);
                setLocationRelativeTo(null);
                refreshDashboardStats();

                // Set the admin name in the label
                jLabel20.setText(adminName);
        }

        /**
         * Creates new form ADMIN - with just clientId
         */
        public AdminPage(int clientId) {
                this.clientId = clientId;
                this.adminName = "Administrator";
                initComponents();
                setSize(1200, 601);
                setLocationRelativeTo(null);
                refreshDashboardStats();

                // Set default admin name
                jLabel20.setText(adminName);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton12 = new javax.swing.JButton();
                jButton13 = new javax.swing.JButton();
                jButton15 = new javax.swing.JButton();
                jButton16 = new javax.swing.JButton();
                jButton17 = new javax.swing.JButton();
                jButton11 = new RoundedButton(20);
                jScrollPane2 = new javax.swing.JScrollPane();
                jPanel12 = new javax.swing.JPanel();
                jPanel13 = new RoundedPanel(20);
                jLabel18 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                jButton18 = new RoundedButton(20);
                jButton19 = new RoundedButton(20);
                jLabel20 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                jPanel14 = new RoundedPanel(20);
                jLabel22 = new javax.swing.JLabel();
                jLabel23 = new javax.swing.JLabel();
                jLabel24 = new javax.swing.JLabel();
                jPanel15 = new RoundedPanel(20);
                jLabel25 = new javax.swing.JLabel();
                jLabel26 = new javax.swing.JLabel();
                jLabel27 = new javax.swing.JLabel();
                jPanel16 = new RoundedPanel(20);
                jLabel28 = new javax.swing.JLabel();
                jLabel29 = new javax.swing.JLabel();
                jLabel30 = new javax.swing.JLabel();
                jPanel17 = new RoundedPanel(20);
                jLabel31 = new javax.swing.JLabel();
                jButton20 = new RoundedButton(20);
                jButton21 = new RoundedButton(20);
                jButton22 = new RoundedButton(20);
                jPanel18 = new RoundedPanel(20);
                jLabel32 = new javax.swing.JLabel();
                jButton23 = new RoundedButton(20);
                jButton24 = new RoundedButton(20);
                jButton25 = new RoundedButton(20);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(null);
                jPanel1.setBackground(new java.awt.Color(24, 24, 24));
                jPanel4.setBackground(new java.awt.Color(24, 24, 24));
                jPanel4.setBorder(null);
                jPanel1.setLayout(new java.awt.BorderLayout());

                jPanel4.setLayout(new java.awt.BorderLayout());

                jPanel3.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/image.jpg"))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                jLabel2.setText("Administrator");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(102, 102, 102)
                                                                                                .addComponent(jLabel1))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(87, 87, 87)
                                                                                                .addComponent(jLabel2)))
                                                                .addContainerGap(90, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                89,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel2)
                                                                .addContainerGap()));

                jPanel4.add(jPanel3, java.awt.BorderLayout.NORTH);

                jPanel2.setBackground(new java.awt.Color(24, 24, 24));
                jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(120, 120, 120)));

                jButton1.setBackground(new java.awt.Color(24, 24, 24));
                jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/hhhhhhhhh.png"))); // NOI18N
                jButton1.setText("Dashboard");
                jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton1.setBorderPainted(false);
                jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton1.setIconTextGap(19);
                jButton1.setMargin(new java.awt.Insets(2, 24, 2, 14));
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton3.setBackground(new java.awt.Color(24, 24, 24));
                jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/rating.png"))); // NOI18N
                jButton3.setText("View Clients");
                jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton3.setIconTextGap(19);
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton12.setBackground(new java.awt.Color(24, 24, 24));
                jButton12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton12.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/layout/Icons/plusuuuuuuuuuuuuuu.png"))); // NOI18N
                jButton12.setText("Add Admin");
                jButton12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton12.setBorderPainted(false);
                jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton12.setIconTextGap(19);
                jButton12.setMargin(new java.awt.Insets(2, 24, 2, 14));
                jButton12.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton12ActionPerformed(evt);
                        }
                });

                jButton13.setBackground(new java.awt.Color(24, 24, 24));
                jButton13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton13.setIcon(
                                new javax.swing.ImageIcon(
                                                getClass().getResource("/layout/Icons/dgfgfhmchgthtdfhrhdfhjthf.png"))); // NOI18N
                jButton13.setText("Cars for Sale");
                jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton13.setIconTextGap(19);
                jButton13.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton13ActionPerformed(evt);
                        }
                });

                jButton15.setBackground(new java.awt.Color(24, 24, 24));
                jButton15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/admin.png"))); // NOI18N
                jButton15.setText("View Admins");
                jButton15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton15.setIconTextGap(19);
                jButton15.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton15ActionPerformed(evt);
                        }
                });

                jButton16.setBackground(new java.awt.Color(24, 24, 24));
                jButton16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/deal.png"))); // NOI18N
                jButton16.setText("Cars for Rent");
                jButton16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton16.setIconTextGap(19);
                jButton16.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton16ActionPerformed(evt);
                        }
                });

                jButton17.setBackground(new java.awt.Color(24, 24, 24));
                jButton17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/chatting.png"))); // NOI18N
                jButton17.setText("Messages");
                jButton17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton17.setIconTextGap(19);
                jButton17.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton17ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE)
                                                .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE)
                                                .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE)
                                                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(9, 9, 9)
                                                                .addComponent(jButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jButton15,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton13,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton16,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton17,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                56,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                61,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

                jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

                jButton11.setBackground(new java.awt.Color(24, 24, 24));
                jButton11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/hhhhhhhhh.png"))); // NOI18N
                jButton11.setText("Dashboard");
                jButton11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                jButton11.setBorderPainted(false);
                jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jButton11.setIconTextGap(19);
                jButton11.setMargin(new java.awt.Insets(2, 24, 2, 14));
                jButton11.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton11ActionPerformed(evt);
                        }
                });
                jPanel1.add(jButton11);
                jButton11.setBounds(0, 0, 152, 26);

                jScrollPane2.setBorder(null);
                jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
                jScrollPane2.setViewportBorder(null);

                jPanel12.setBackground(new java.awt.Color(52, 52, 52));
                jPanel12.setBorder(null);
                jPanel12.setForeground(new java.awt.Color(51, 51, 51));
                jPanel12.setPreferredSize(new java.awt.Dimension(852, 790));

                jPanel13.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel18.setText("Welcome Back, Admin!");

                jLabel19.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
                jLabel19.setText("Here's what's happening with your car business today.");

                jButton18.setBackground(new java.awt.Color(255, 0, 0));
                jButton18.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
                jButton18.setText("Logout");
                jButton18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jButton18.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton18ActionPerformed(evt);
                        }
                });

                jButton19.setBackground(new java.awt.Color(0, 102, 255));
                jButton19.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
                jButton19.setText("Profile");
                jButton19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jButton19.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton19ActionPerformed(evt);
                        }
                });

                jLabel20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
                jLabel20.setText("admin_name");

                                                // Set admin profile picture if available, else default
                                                String profilePicPath = null;
                                                                try {
                                                                        Connection conn = config.getConnection();
                                                                        Statement stmt = conn.createStatement();
                                                                        ResultSet rs = stmt.executeQuery("SELECT profile_image FROM client WHERE client_id = " + clientId);
                                                                        if (rs.next()) {
                                                                                profilePicPath = rs.getString("profile_image");
                                                                        }
                                                                        rs.close();
                                                                        stmt.close();
                                                                        conn.close();
                                                                } catch (Exception e) { profilePicPath = null; }
                                                if (profilePicPath != null && !profilePicPath.isEmpty()) {
                                                        ImageIcon icon = new ImageIcon(profilePicPath);
                                                        Image img = icon.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
                                                        jLabel21.setIcon(new ImageIcon(img));
                                                } else {
                                                        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/user2.png")));
                                                }

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel13Layout.createSequentialGroup()
                                                                .addGroup(jPanel13Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel13Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(23, 23, 23)
                                                                                                .addComponent(jLabel18))
                                                                                .addGroup(jPanel13Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel19)))
                                                                .addGap(154, 154, 154)
                                                                .addComponent(jLabel21)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel20)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton19,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                68,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton18,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                67,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(23, 23, 23)));
                jPanel13Layout.setVerticalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel13Layout.createSequentialGroup()
                                                                .addGroup(jPanel13Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel13Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel18)
                                                                                                .addGap(9, 9, 9)
                                                                                                .addComponent(jLabel19))
                                                                                .addGroup(jPanel13Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(jPanel13Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addContainerGap()
                                                                                                                .addComponent(jLabel21,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                25,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                jPanel13Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(35, 35, 35)
                                                                                                                                .addGroup(jPanel13Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jButton18,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                25,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jButton19,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                25,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel20)))))
                                                                .addContainerGap(35, Short.MAX_VALUE)));

                jPanel14.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/firari.png"))); // NOI18N

                jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel23.setText("Total Cars Available");

                jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addGroup(jPanel14Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel14Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(50, 50, 50)
                                                                                                .addComponent(jLabel23))
                                                                                .addGroup(jPanel14Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(81, 81, 81)
                                                                                                .addComponent(jLabel22))
                                                                                .addGroup(jPanel14Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(103, 103, 103)
                                                                                                .addComponent(jLabel24)))
                                                                .addContainerGap(39, Short.MAX_VALUE)));
                jPanel14Layout.setVerticalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addComponent(jLabel22,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                72,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                19,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel24)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel23)
                                                                .addContainerGap()));

                jPanel15.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/money-bags.png"))); // NOI18N

                jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel26.setText("Cars Sold");

                jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel15Layout.createSequentialGroup()
                                                                .addContainerGap(68, Short.MAX_VALUE)
                                                                .addGroup(jPanel15Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel15Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel27)
                                                                                                                .addGap(98, 98, 98))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel15Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel25)
                                                                                                                .addGap(83, 83, 83))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel15Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel26,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                92,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(67, 67, 67)))));
                jPanel15Layout.setVerticalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel15Layout.createSequentialGroup()
                                                                .addComponent(jLabel25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                72,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                19,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel27)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel26)
                                                                .addContainerGap()));

                jPanel16.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/clientspic.png"))); // NOI18N

                jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel29.setText("Total Clients");

                jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel16Layout.createSequentialGroup()
                                                                .addGroup(jPanel16Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(69, 69, 69)
                                                                                                .addComponent(jLabel29))
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(101, 101, 101)
                                                                                                .addComponent(jLabel30))
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(79, 79, 79)
                                                                                                .addComponent(jLabel28)))
                                                                .addContainerGap(69, Short.MAX_VALUE)));
                jPanel16Layout.setVerticalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel16Layout.createSequentialGroup()
                                                                .addComponent(jLabel28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                12,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel30)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel29)
                                                                .addContainerGap()));

                jPanel17.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel31.setText("Quick Actions - Car Management");

                jButton20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton20.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/layout/Icons/plusuuuuuuuuuuuuuu.png"))); // NOI18N
                jButton20.setText("Add New Car");
                // jButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24, 24, 24)));
                jButton20.setIconTextGap(19);
                jButton20.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton20ActionPerformed(evt);
                        }
                });

                jButton21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/check-list.png"))); // NOI18N
                jButton21.setText("View All Cars");
                // jButton21.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24, 24, 24)));
                jButton21.setIconTextGap(19);
                jButton21.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton21ActionPerformed(evt);
                        }
                });

                jButton22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/edit.png"))); // NOI18N
                jButton22.setText("Edit Car Data");
                // jButton22.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24, 24, 24)));
                jButton22.setIconTextGap(19);
                jButton22.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton22ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel17Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel17Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jButton22,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jButton21,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jButton20,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel31,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel17Layout.setVerticalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel17Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton20,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jButton21,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jButton22,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel18.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel32.setText("Quick Actions - Business Operations");

                jButton23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/minus-button.png"))); // NOI18N
                jButton23.setText("Remove Client");
                // jButton23.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24,24,24)));
                jButton23.setIconTextGap(19);
                jButton23.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton23ActionPerformed(evt);
                        }
                });

                jButton24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/check-list.png"))); // NOI18N
                jButton24.setText("View All Client");
                // jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24,24,24)));
                jButton24.setIconTextGap(19);
                jButton24.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton24ActionPerformed(evt);
                        }
                });

                jButton25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/sand-clock.png"))); // NOI18N
                jButton25.setText("Client Approvals");
                // jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24,24,24)));
                jButton25.setIconTextGap(19);
                jButton25.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton25ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                jPanel18.setLayout(jPanel18Layout);
                jPanel18Layout.setHorizontalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel18Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel18Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel32,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jButton23,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jButton24,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jButton25,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel18Layout.setVerticalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel18Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton24,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton23,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)));

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
    jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                // Evenly distributed panels with equal spacing
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(48, Short.MAX_VALUE)));
                jPanel12Layout.setVerticalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel13,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel12Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jPanel14,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel15,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel16,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jPanel17,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel18,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(16, Short.MAX_VALUE)));

                jScrollPane2.setViewportView(jPanel12);

                jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

                getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>

        // Button Action Methods - All buttons are now functional

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                // Dashboard - refresh the current page
                JOptionPane.showMessageDialog(this, "Dashboard refreshed!", "Dashboard",
                                JOptionPane.INFORMATION_MESSAGE);
        }

        private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
                // Duplicate Dashboard button - same functionality as jButton1
                JOptionPane.showMessageDialog(this, "Dashboard refreshed!", "Dashboard",
                                JOptionPane.INFORMATION_MESSAGE);
        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
                // View Clients
                try {
                        ViewClientsPage viewClientsPage = new ViewClientsPage();
                        viewClientsPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening View Clients page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {
                // View All Clients - same as jButton3
                try {
                        ViewClientsPage viewClientsPage = new ViewClientsPage();
                        viewClientsPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening View Clients page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
                // Cars for Sale
                try {
                        // Create a placeholder page or open actual CarsForSalePage
                        JOptionPane.showMessageDialog(this, "Opening Cars for Sale page...",
                                        "Cars for Sale", JOptionPane.INFORMATION_MESSAGE);
                        // Uncomment when you have the actual page:
                        // CarsForSalePage carsForSalePage = new CarsForSalePage();
                        // carsForSalePage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Cars for Sale page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
                // View Admins
                try {
                        ViewAdminsPage viewAdminsPage = new ViewAdminsPage();
                        viewAdminsPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening View Admins page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
                // Cars for Rent
                try {
                        JOptionPane.showMessageDialog(this, "Opening Cars for Rent page...",
                                        "Cars for Rent", JOptionPane.INFORMATION_MESSAGE);
                        // Uncomment when you have the actual page:
                        // CarsForRentPage carsForRentPage = new CarsForRentPage();
                        // carsForRentPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Cars for Rent page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
                // Messages
                try {
                        JOptionPane.showMessageDialog(this, "Opening Messages page...",
                                        "Messages", JOptionPane.INFORMATION_MESSAGE);
                        // Uncomment when you have the actual page:
                        // MessagesPage messagesPage = new MessagesPage();
                        // messagesPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Messages page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
                // Logout
                int confirm = JOptionPane.showConfirmDialog(this,
                                "Are you sure you want to logout?",
                                "Confirm Logout",
                                JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                        this.dispose();
                        try {
                                LoginFrame loginFrame = new LoginFrame();
                                loginFrame.setSize(1280, 750);
                                loginFrame.setResizable(false);
                                loginFrame.setVisible(true);
                                loginFrame.setLocationRelativeTo(null);
                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Error opening Login page: " + e.getMessage(),
                                                "Error", JOptionPane.ERROR_MESSAGE);
                        }
                }
        }

        private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
                // Profile
                try {
                        AdminProfilePage profilePage = new AdminProfilePage(this.clientId);
                        profilePage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Profile page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
                // Add New Car
                try {
                        JOptionPane.showMessageDialog(this, "Opening Add New Car page...",
                                        "Add Car", JOptionPane.INFORMATION_MESSAGE);
                        // Uncomment when you have the actual page:
                        // AddCarPage addCarPage = new AddCarPage();
                        // addCarPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Add Car page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {
                // View All Cars
                try {
                        JOptionPane.showMessageDialog(this, "Opening View All Cars page...",
                                        "View Cars", JOptionPane.INFORMATION_MESSAGE);
                        // Uncomment when you have the actual page:
                        // ViewAllCarsPage viewCarsPage = new ViewAllCarsPage();
                        // viewCarsPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening View Cars page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {
                // Edit Car Data
                try {
                        JOptionPane.showMessageDialog(this, "Opening Edit Car Data page...",
                                        "Edit Car", JOptionPane.INFORMATION_MESSAGE);
                        // Uncomment when you have the actual page:
                        // EditCarPage editCarPage = new EditCarPage();
                        // editCarPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Edit Car page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {
                // Remove Client
                try {
                        DeleteClientPage deleteClientPage = new DeleteClientPage();
                        deleteClientPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Delete Client page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {
                try {
                        ApprovalPage approvalPage = new ApprovalPage();
                        approvalPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Approval page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
                // Add Admin
                try {
                        this.showTemporaryDialog("Opening Add Admin...", new Runnable() {
                                public void run() {
                                        AddAdminPage addAdminPage = new AddAdminPage();
                                        addAdminPage.setVisible(true);
                                }
                        });
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Add Admin page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * Show a modal loading dialog while running a small open action.
         * The provided Runnable will be executed on the Event Dispatch Thread
         * after the background worker completes (so UI creation happens safely).
         */
        private void showTemporaryDialog(String message, final Runnable onOpen) {
                final JDialog dialog = new JDialog(this, "Please wait", true);
                JPanel p = new JPanel(new BorderLayout(8, 8));
                p.add(new JLabel(message), BorderLayout.CENTER);
                JProgressBar bar = new JProgressBar();
                bar.setIndeterminate(true);
                p.add(bar, BorderLayout.SOUTH);
                dialog.getContentPane().add(p);
                dialog.pack();
                dialog.setLocationRelativeTo(this);

                SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                        @Override
                        protected Void doInBackground() throws Exception {
                                // nothing heavy here; keep worker so dialog can show
                                return null;
                        }

                        @Override
                        protected void done() {
                                try {
                                        // Create/show page on EDT (this runs on EDT)
                                        if (onOpen != null) {
                                                onOpen.run();
                                        }
                                } catch (Exception e) {
                                        JOptionPane.showMessageDialog(AdminPage.this,
                                                        "Error opening page: " + e.getMessage(), "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                } finally {
                                        dialog.dispose();
                                }
                        }
                };

                worker.execute();
                dialog.setVisible(true);
        }

        // Helper method to refresh dashboard statistics (optional)
        private void refreshDashboardStats() {
                try (Connection conn = config.getConnection();
                                Statement stmt = conn.createStatement()) {

                        // ✅ Total Cars Available
                        ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS total FROM car");
                        if (rs.next()) {
                                jLabel24.setText(String.valueOf(rs.getInt("total")));
                        }
                        rs.close();

                        // ✅ Cars Sold
                        rs = stmt.executeQuery("SELECT COUNT(*) AS total FROM sale");
                        if (rs.next()) {
                                jLabel27.setText(String.valueOf(rs.getInt("total")));
                        }
                        rs.close();

                        // ✅ Total Clients (excluding admins)
                        rs = stmt.executeQuery("SELECT COUNT(*) AS total FROM client WHERE role != 'admin'");
                        if (rs.next()) {
                                jLabel30.setText(String.valueOf(rs.getInt("total")));
                        }
                        rs.close();

                } catch (Exception e) {
                        System.err.println("Error refreshing dashboard stats: " + e.getMessage());
                }
        }

        // Getters for admin information
        public int getClientId() {
                return clientId;
        }

        public String getAdminName() {
                return adminName;
        }

        // Setter methods to update admin information
        public void setClientId(int clientId) {
                this.clientId = clientId;
        }

        public void setAdminName(String adminName) {
                this.adminName = adminName;
                jLabel20.setText(adminName);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (Exception e) {
                        e.printStackTrace();
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AdminPage().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton11;
        private javax.swing.JButton jButton12;
        private javax.swing.JButton jButton13;
        private javax.swing.JButton jButton15;
        private javax.swing.JButton jButton16;
        private javax.swing.JButton jButton17;
        private javax.swing.JButton jButton18;
        private javax.swing.JButton jButton19;
        private javax.swing.JButton jButton20;
        private javax.swing.JButton jButton21;
        private javax.swing.JButton jButton22;
        private javax.swing.JButton jButton23;
        private javax.swing.JButton jButton24;
        private javax.swing.JButton jButton25;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel27;
        private javax.swing.JLabel jLabel28;
        private javax.swing.JLabel jLabel29;
        private javax.swing.JLabel jLabel30;
        private javax.swing.JLabel jLabel31;
        private javax.swing.JLabel jLabel32;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel18;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane2;
        // End of variables declaration
}