/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import functions.RoundedButton;

/**
 *
 * @author samih
 */

public class AdminPage extends javax.swing.JFrame {

        /**
         * Creates new form ADMIN
         */
        private int clientId;
        private String adminName;
        private JPanel mainPanel;
        private Connection dbConn;
        private ViewClientsPanel viewClientsPanel;
        private ViewAdminsPanel viewAdminsPanel;
        private ViewCarsPanel viewCarsPanel;
        private AddAdminPanel addAdminPanel;
        private ViewMessagesPanel viewMessagesPanel;
        private AddCarPanel addCarPanel;

        /**
         * Creates new form ADMIN - default constructor
         */
        public AdminPage() {
                this.clientId = 0;
                this.adminName = "Administrator";
                initComponents();
                setSize(1200, 601);
                setLocationRelativeTo(null);
                refreshDashboardStats(clientId);
                jLabel20.setText(adminName);
                setupMainPanel();
        }

        /**
         * Creates new form ADMIN - with admin name (used by login)
         */
        public AdminPage(int clientId, String adminName) {
                this.clientId = clientId;
                this.adminName = adminName;
                initComponents();
                setSize(1200, 601);
                setLocationRelativeTo(null);
                refreshDashboardStats(clientId);
                jLabel20.setText(adminName);
                setupMainPanel();
        }

        /**
         * Creates new form ADMIN - with just clientId
         */
        public AdminPage(int clientId) {
                this.clientId = clientId;
                this.adminName = "Administrator";
                initComponents();
                setSize(1200, 601);
                setLocationRelativeTo(null);
                refreshDashboardStats(clientId);
                jLabel20.setText(adminName);
                setupMainPanel();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                DashBoardBtn = new javax.swing.JButton();
                ClientsBtn = new javax.swing.JButton();
                CarsBtn = new javax.swing.JButton();
                AdminsBtn = new javax.swing.JButton();
                SupportBtn = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jPanel12 = new javax.swing.JPanel();
                jPanel13 = new RoundedPanel(20);
                jLabel18 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                LogoutBtn = new RoundedButton(20);
                ProfileBtn = new RoundedButton(20);
                jLabel20 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                jPanel14 = new RoundedPanel(20);
                jLabel22 = new javax.swing.JLabel();
                jLabel23 = new javax.swing.JLabel();
                jLabel24 = new javax.swing.JLabel();
                jPanel15 = new RoundedPanel(20);
                jLabel25 = new javax.swing.JLabel();
                jLabel26 = new javax.swing.JLabel();
                jLabel27 = new javax.swing.JLabel();
                jPanel16 = new RoundedPanel(20);
                jLabel28 = new javax.swing.JLabel();
                jLabel29 = new javax.swing.JLabel();
                jLabel30 = new javax.swing.JLabel();
                jPanel17 = new RoundedPanel(20);
                jLabel31 = new javax.swing.JLabel();
                AddCarsBtn = new RoundedButton(20);
                ReportedCarsBtn = new RoundedButton(20);
                jPanel18 = new RoundedPanel(20);
                jLabel32 = new javax.swing.JLabel();
                AddAdminQuickActionsBtn = new RoundedButton(20);
                PendinApprovalsBtn = new RoundedButton(20);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(null);
                jPanel1.setBackground(new java.awt.Color(24, 24, 24));
                jPanel4.setBackground(new java.awt.Color(24, 24, 24));
                jPanel4.setBorder(null);
                jPanel1.setLayout(new java.awt.BorderLayout());

                jPanel4.setLayout(new java.awt.BorderLayout());

                jPanel3.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/image.jpg"))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                jLabel2.setText("Administrator");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(102, 102, 102)
                                                                                                .addComponent(jLabel1))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(87, 87, 87)
                                                                                                .addComponent(jLabel2)))
                                                                .addContainerGap(90, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                89,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel2)
                                                                .addContainerGap()));

                jPanel4.add(jPanel3, java.awt.BorderLayout.NORTH);

                jPanel2.setBackground(new java.awt.Color(24, 24, 24));
                jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0,
                                new java.awt.Color(120, 120, 120)));

                DashBoardBtn.setBackground(new java.awt.Color(24, 24, 24));
                DashBoardBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                DashBoardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/hhhhhhhhh.png"))); // NOI18N
                DashBoardBtn.setText("Dashboard");
                DashBoardBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                DashBoardBtn.setBorderPainted(false);
                DashBoardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                DashBoardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                DashBoardBtn.setIconTextGap(19);
                DashBoardBtn.setMargin(new java.awt.Insets(2, 24, 2, 14));
                DashBoardBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                // Show dashboard panel or perform intended action
                                showPanel("dashboard");
                                // Trigger an explicit refresh (async) when user clicks sidebar Dashboard
                                new SwingWorker<Void, Void>() {
                                        @Override
                                        protected Void doInBackground() throws Exception {
                                                refreshDashboardStats(clientId);
                                                return null;
                                        }
                                }.execute();
                        }
                });

                ClientsBtn.setBackground(new java.awt.Color(24, 24, 24));
                ClientsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                ClientsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/rating.png"))); // NOI18N
                ClientsBtn.setText("Clients");
                ClientsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                ClientsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                ClientsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                ClientsBtn.setIconTextGap(19);
                ClientsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ClientsBtnActionPerformed(evt);
                        }
                });

                CarsBtn.setBackground(new java.awt.Color(24, 24, 24));
                CarsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                CarsBtn.setIcon(
                                new javax.swing.ImageIcon(
                                                getClass().getResource("/layout/Icons/dgfgfhmchgthtdfhrhdfhjthf.png"))); // NOI18N
                CarsBtn.setText("Cars");
                CarsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                CarsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                CarsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                CarsBtn.setIconTextGap(19);
                CarsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CarsBtnActionPerformed(evt);
                        }
                });

                AdminsBtn.setBackground(new java.awt.Color(24, 24, 24));
                AdminsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                AdminsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/admin.png"))); // NOI18N
                AdminsBtn.setText("Admins");
                AdminsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                AdminsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                AdminsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                AdminsBtn.setIconTextGap(19);
                AdminsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AdminsBtnActionPerformed(evt);
                        }
                });

                SupportBtn.setBackground(new java.awt.Color(24, 24, 24));
                SupportBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                SupportBtn.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/risk-analysis.png"))); // NOI18N
                SupportBtn.setText("Reports");
                SupportBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
                SupportBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                SupportBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                SupportBtn.setIconTextGap(19);
                SupportBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SupportBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ClientsBtn, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE)
                                                .addComponent(DashBoardBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                // Removed jButton12 (Add Admin)
                                                .addComponent(CarsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE)
                                                .addComponent(AdminsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE)
                                                .addComponent(SupportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 318,
                                                                Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(DashBoardBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(9, 9, 9)
                                                                .addComponent(ClientsBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(8, 8, 8)
                                                                .addComponent(AdminsBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(CarsBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(SupportBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                56,
                                                                                Short.MAX_VALUE)));

                jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

                jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

                jScrollPane2.setBorder(null);
                jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
                jScrollPane2.setViewportBorder(null);

                jPanel12.setBackground(new java.awt.Color(52, 52, 52));
                jPanel12.setBorder(null);
                jPanel12.setForeground(new java.awt.Color(51, 51, 51));
                jPanel12.setPreferredSize(new java.awt.Dimension(852, 790));

                jPanel13.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel18.setText("Welcome Back, Admin!");

                jLabel19.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
                jLabel19.setText("Here's what's happening with your car business today.");

                LogoutBtn.setBackground(new java.awt.Color(255, 0, 0));
                LogoutBtn.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
                LogoutBtn.setText("Logout");
                LogoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogoutBtnActionPerformed(evt);
                        }
                });

                ProfileBtn.setBackground(new java.awt.Color(0, 102, 255));
                ProfileBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
                ProfileBtn.setText("Profile");
                ProfileBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                ProfileBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ProfileBtnActionPerformed(evt);
                        }
                });

                jLabel20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
                jLabel20.setText("admin_name");

                // Set admin profile picture if available, else default
                String profilePicPath = null;
                try {
                        Connection conn = config.getConnection();
                        Statement stmt = conn.createStatement();
                        ResultSet rs = stmt
                                        .executeQuery("SELECT profile_image FROM client WHERE client_id = " + clientId);
                        if (rs.next()) {
                                profilePicPath = rs.getString("profile_image");
                        }
                        rs.close();
                        stmt.close();
                        conn.close();
                } catch (Exception e) {
                        profilePicPath = null;
                }
                if (profilePicPath != null && !profilePicPath.isEmpty()) {
                        File imgFile = new File(profilePicPath);
                        if (imgFile.exists()) {
                                ImageIcon icon = new ImageIcon(imgFile.getAbsolutePath());
                                Image img = icon.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
                                jLabel21.setIcon(new ImageIcon(img));
                        } else {
                                jLabel21.setIcon(new javax.swing.ImageIcon(
                                                getClass().getResource("/layout/Icons/user2.png")));
                        }
                } else {
                        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/user2.png")));
                }

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel13Layout.createSequentialGroup()
                                                                .addGroup(jPanel13Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel13Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(23, 23, 23)
                                                                                                .addComponent(jLabel18))
                                                                                .addGroup(jPanel13Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel19)))
                                                                .addGap(154, 154, 154)
                                                                .addComponent(jLabel21)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel20)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(ProfileBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                68,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(LogoutBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                67,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(23, 23, 23)));
                jPanel13Layout.setVerticalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel13Layout.createSequentialGroup()
                                                                .addGroup(jPanel13Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel13Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel18)
                                                                                                .addGap(9, 9, 9)
                                                                                                .addComponent(jLabel19))
                                                                                .addGroup(jPanel13Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(jPanel13Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addContainerGap()
                                                                                                                .addComponent(jLabel21,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                25,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                jPanel13Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(35, 35, 35)
                                                                                                                                .addGroup(jPanel13Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(LogoutBtn,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                25,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(ProfileBtn,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                25,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel20)))))
                                                                .addContainerGap(35, Short.MAX_VALUE)));

                jPanel14.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/firari.png"))); // NOI18N

                jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel23.setText("Total Cars Available");

                jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addGroup(jPanel14Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel14Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(50, 50, 50)
                                                                                                .addComponent(jLabel23))
                                                                                .addGroup(jPanel14Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(81, 81, 81)
                                                                                                .addComponent(jLabel22))
                                                                                .addGroup(jPanel14Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(103, 103, 103)
                                                                                                .addComponent(jLabel24)))
                                                                .addContainerGap(39, Short.MAX_VALUE)));
                jPanel14Layout.setVerticalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addComponent(jLabel22,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                72,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                19,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel24)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel23)
                                                                .addContainerGap()));

                jPanel15.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/hourglass.png"))); // NOI18N

                jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel26.setText("User Queue");

                jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel27.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel15Layout.createSequentialGroup()
                                                                .addContainerGap(68, Short.MAX_VALUE)
                                                                .addGroup(jPanel15Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel15Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel27)
                                                                                                                .addGap(111, 111,
                                                                                                                                111))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel15Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel25)
                                                                                                                .addGap(83, 83, 83))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel15Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel26,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                92,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(67, 67, 67)))));
                jPanel15Layout.setVerticalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel15Layout.createSequentialGroup()
                                                                .addComponent(jLabel25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                72,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                19,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel27)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel26)
                                                                .addContainerGap()));

                jPanel16.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/clientspic.png"))); // NOI18N

                jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel29.setText("Total Clients");

                jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel16Layout.createSequentialGroup()
                                                                .addGroup(jPanel16Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(69, 69, 69)
                                                                                                .addComponent(jLabel29))
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(100, 100, 100)
                                                                                                .addComponent(jLabel30))

                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(79, 79, 79)
                                                                                                .addComponent(jLabel28)))
                                                                .addContainerGap(69, Short.MAX_VALUE)));
                jPanel16Layout.setVerticalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel16Layout.createSequentialGroup()
                                                                .addComponent(jLabel28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                12,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel30)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel29)
                                                                .addContainerGap()));

                jPanel17.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel31.setText("Quick Actions - Cars -");

                AddCarsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                AddCarsBtn.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/layout/Icons/plusuuuuuuuuuuuuuu.png"))); // NOI18N
                AddCarsBtn.setText("Add New Car");
                // AddCarsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24, 24, 24)));
                AddCarsBtn.setIconTextGap(19);
                AddCarsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AddCarsBtnActionPerformed(evt);
                        }
                });

                ReportedCarsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                ReportedCarsBtn.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/check-list.png"))); // NOI18N
                ReportedCarsBtn.setText("Reported Cars");
                // ReportedCarsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24, 24, 24)));
                ReportedCarsBtn.setIconTextGap(19);
                ReportedCarsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReportedCarsBtnActionPerformed(evt);
                        }
                });

                // jButton22 (Manage Users) removed from Quick Actions

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel17Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel17Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(ReportedCarsBtn,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(AddCarsBtn,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel31,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel17Layout.setVerticalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel17Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(AddCarsBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(ReportedCarsBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel18.setBackground(new java.awt.Color(24, 24, 24));
                // jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(0, 0, 0)));

                jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel32.setText("Quick Actions - Clients & Admins -");

                AddAdminQuickActionsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                AddAdminQuickActionsBtn.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/layout/Icons/plusuuuuuuuuuuuuuu.png"))); // NOI18N
                AddAdminQuickActionsBtn.setText("Add New Admin");
                // AddAdminQuickActionsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24,24,24)));
                AddAdminQuickActionsBtn.setIconTextGap(19);
                AddAdminQuickActionsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AddAdminQuickActionsBtnActionPerformed(evt);
                        }
                });

                // jButton24 (View All Client) removed from Quick Actions

                PendinApprovalsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                PendinApprovalsBtn.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/layout/Icons/sand-clock.png"))); // NOI18N
                PendinApprovalsBtn.setText("Pending Approvals");
                // PendinApprovalsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new
                // java.awt.Color(24,24,24)));
                PendinApprovalsBtn.setIconTextGap(19);
                PendinApprovalsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PendinApprovalsBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                jPanel18.setLayout(jPanel18Layout);
                jPanel18Layout.setHorizontalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel18Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel18Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel32,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(AddAdminQuickActionsBtn,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(PendinApprovalsBtn,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel18Layout.setVerticalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel18Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(AddAdminQuickActionsBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(PendinApprovalsBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)));

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addGap(51, 51, 51)
                                                                .addGroup(jPanel12Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                // Evenly distributed panels with equal
                                                                                // spacing
                                                                                .addGroup(jPanel12Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jPanel14,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jPanel15,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jPanel16,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jPanel13,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel17,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel18,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(48, Short.MAX_VALUE)));
                jPanel12Layout.setVerticalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel13,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel12Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jPanel14,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel15,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel16,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jPanel17,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel18,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(16, Short.MAX_VALUE)));

                jScrollPane2.setViewportView(jPanel12);

                jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

                // Replace direct add with mainPanel
                mainPanel = new JPanel(new java.awt.CardLayout());
                mainPanel.add(jPanel1, "dashboard");
                getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
                pack();
        }// </editor-fold>

        // Button Action Methods - All buttons are now functional

        private void ClientsBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // Show ViewClientsPanel in mainPanel
                showPanel("clients");
        }

        // jButton24 (View All Client) action removed

        private void CarsBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // Show ViewCarsPanel in mainPanel
                showPanel("cars");
        }

        private void AdminsBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // Show ViewAdminsPanel in mainPanel
                showPanel("admins");
        }

        private void SupportBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // Show ViewMessagesPanel in mainPanel
                showPanel("messages");
        }

        private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // Logout
                int confirm = JOptionPane.showConfirmDialog(this,
                                "Are you sure you want to logout?",
                                "Confirm Logout",
                                JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                        // Close database connection before logout
                        closeDatabaseConnection();
                        this.dispose();
                        try {
                                LoginFrame loginFrame = new LoginFrame();
                                loginFrame.setSize(1280, 750);
                                loginFrame.setResizable(false);
                                loginFrame.setVisible(true);
                                loginFrame.setLocationRelativeTo(null);
                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Error opening Login page: " + e.getMessage(),
                                                "Error", JOptionPane.ERROR_MESSAGE);
                        }
                }
        }

        private void ProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // Profile
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                ProfilePanelsami profile = new ProfilePanelsami(clientId);
                                profile.setLocationRelativeTo(AdminPage.this);
                                profile.setVisible(true);
                        }
                });
        }

        private void AddCarsBtnActionPerformed(java.awt.event.ActionEvent evt) {
            JDialog dialog = new JDialog(this, "Add New Car", true);
            // Reuse the existing addCarPanel and clear the form
            if (addCarPanel != null) {
                // Clear the form fields before showing
                addCarPanel.clearForm();
                dialog.add(addCarPanel);
                dialog.setSize(1200, 800);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
            } else {
                // Fallback: create new panel if somehow addCarPanel is null
                AddCarPanel carPanel = new AddCarPanel(dbConn, clientId);
                dialog.add(carPanel);
                dialog.setSize(1200, 800);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
            }
        }

        private void ReportedCarsBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // View All Cars
                try {
                        JOptionPane.showMessageDialog(this, "Opening View All Cars page...",
                                        "View Cars", JOptionPane.INFORMATION_MESSAGE);
                        // Uncomment when you have the actual page:
                        // ViewAllCarsPage viewCarsPage = new ViewAllCarsPage();
                        // viewCarsPage.setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening View Cars page: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        // jButton22 (Manage Users) action removed

        private void AddAdminQuickActionsBtnActionPerformed(java.awt.event.ActionEvent evt) {
                JDialog dialog = new JDialog(this, "Add New Admin", true);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setSize(600, 650);
                dialog.setLocationRelativeTo(this);
                dialog.setLayout(new BorderLayout());
                dialog.add(new AddAdminPanel(dbConn, new Runnable() {
                    @Override
                    public void run() {
                        viewAdminsPanel.refreshData();
                        dialog.dispose();
                    }
                }), BorderLayout.CENTER);
                dialog.setVisible(true);
        }

        private ApprovalPanel approvalPanel;

        private void PendinApprovalsBtnActionPerformed(java.awt.event.ActionEvent evt) {
                try {
                        // Show ApprovalPanel inside mainPanel (fast) - panel was created in
                        // setupMainPanel
                        showPanel("approvals");
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening Pending Approvals: " + e.getMessage(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * Show a modal loading dialog while running a small open action.
         * The provided Runnable will be executed on the Event Dispatch Thread
         * after the background worker completes (so UI creation happens safely).
         */
        private void showTemporaryDialog(String message, final Runnable onOpen) {
                final JDialog dialog = new JDialog(this, "Please wait", true);
                JPanel p = new JPanel(new BorderLayout(8, 8));
                p.add(new JLabel(message), BorderLayout.CENTER);
                JProgressBar bar = new JProgressBar();
                bar.setIndeterminate(true);
                p.add(bar, BorderLayout.SOUTH);
                dialog.getContentPane().add(p);
                dialog.pack();
                dialog.setLocationRelativeTo(this);

                SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                        @Override
                        protected Void doInBackground() throws Exception {
                                // nothing heavy here; keep worker so dialog can show
                                return null;
                        }

                        @Override
                        protected void done() {
                                try {
                                        // Create/show page on EDT (this runs on EDT)
                                        if (onOpen != null) {
                                                onOpen.run();
                                        }
                                } catch (Exception e) {
                                        JOptionPane.showMessageDialog(AdminPage.this,
                                                        "Error opening page: " + e.getMessage(), "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                } finally {
                                        dialog.dispose();
                                }
                        }
                };

                worker.execute();
                dialog.setVisible(true);
        }

        // Helper method to refresh dashboard statistics (optional)
        private void refreshDashboardStats(int clientId) {
                try (Connection conn = config.getConnection();
                                Statement stmt = conn.createStatement()) {

                        // Total Cars Available
                        ResultSet rs = stmt
                                        .executeQuery("SELECT COUNT(*) AS total FROM car WHERE status = 'available'");
                        if (rs.next()) {
                                jLabel24.setText(String.valueOf(rs.getInt("total")));
                        }
                        rs.close();

                        // Client Queue
                        rs = stmt.executeQuery(
                                        "SELECT COUNT(*) AS total FROM client WHERE is_approved = FALSE AND role != 'admin'");
                        if (rs.next()) {
                                jLabel27.setText(String.valueOf(rs.getInt("total")));
                        }
                        rs.close();

                        // Total Clients
                        rs = stmt.executeQuery(
                                        "SELECT COUNT(*) AS total FROM client WHERE is_approved = TRUE AND role != 'admin'");
                        if (rs.next()) {
                                jLabel30.setText(String.valueOf(rs.getInt("total")));
                        }
                        rs.close();

                        // Refresh Profile
                        rs = stmt.executeQuery("SELECT name, profile_image FROM client WHERE client_id = " + clientId);
                        if (rs.next()) {
                                String name = rs.getString("name");
                                String profilePicPath = rs.getString("profile_image");

                                if (jLabel20 != null) {
                                        jLabel20.setText(name);
                                }

                                if (profilePicPath != null && !profilePicPath.isEmpty()) {
                                        File imgFile = new File(profilePicPath);
                                        if (imgFile.exists()) {
                                                ImageIcon icon = new ImageIcon(imgFile.getAbsolutePath());
                                                Image img = icon.getImage().getScaledInstance(25, 25,
                                                                Image.SCALE_SMOOTH);
                                                jLabel21.setIcon(new ImageIcon(img));
                                        } else {
                                                jLabel21.setIcon(new javax.swing.ImageIcon(
                                                                getClass().getResource("/layout/Icons/user2.png")));
                                        }
                                } else {
                                        jLabel21.setIcon(new javax.swing.ImageIcon(
                                                        getClass().getResource("/layout/Icons/user2.png")));
                                }
                        }
                        rs.close();

                } catch (Exception e) {
                        System.err.println("Error refreshing dashboard stats: " + e.getMessage());
                }
        }

        // Getters for admin information
        public int getClientId() {
                return clientId;
        }

        public String getAdminName() {
                return adminName;
        }

        // Setter methods to update admin information
        public void setClientId(int clientId) {
                this.clientId = clientId;
        }

        public void setAdminName(String adminName) {
                this.adminName = adminName;
                jLabel20.setText(adminName);
        }

        /**
         * Close database connection to prevent connection leaks
         */
        private void closeDatabaseConnection() {
                if (dbConn != null) {
                        try {
                                if (!dbConn.isClosed()) {
                                        dbConn.close();
                                        System.out.println("Database connection closed successfully");
                                }
                        } catch (Exception e) {
                                System.err.println("Error closing database connection: " + e.getMessage());
                        }
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (Exception e) {
                        e.printStackTrace();
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AdminPage().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton DashBoardBtn;
        private javax.swing.JButton CarsBtn;
        private javax.swing.JButton AdminsBtn;
        private javax.swing.JButton SupportBtn;
        private javax.swing.JButton LogoutBtn;
        private javax.swing.JButton ProfileBtn;
        private javax.swing.JButton AddCarsBtn;
        private javax.swing.JButton ReportedCarsBtn;
        // jButton22 removed
        private javax.swing.JButton AddAdminQuickActionsBtn;
        // jButton24 removed
        private javax.swing.JButton PendinApprovalsBtn;
        private javax.swing.JButton ClientsBtn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel27;
        private javax.swing.JLabel jLabel28;
        private javax.swing.JLabel jLabel29;
        private javax.swing.JLabel jLabel30;
        private javax.swing.JLabel jLabel31;
        private javax.swing.JLabel jLabel32;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel18;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane2;

        // End of variables declaration
        /**
         * Setup mainPanel and ViewClientsPanel for switching views
         */
        private void setupMainPanel() {
                try {
                        dbConn = config.getConnection();
                } catch (Exception e) {
                        dbConn = null;
                        System.err.println("Failed to establish database connection: " + e.getMessage());
                }

                viewClientsPanel = new ViewClientsPanel(dbConn);
                viewAdminsPanel = new ViewAdminsPanel(dbConn);
                viewCarsPanel = new ViewCarsPanel(dbConn);
                viewMessagesPanel = new ViewMessagesPanel(dbConn);
                approvalPanel = new ApprovalPanel(dbConn);
                addCarPanel = new AddCarPanel(dbConn, clientId);
                addAdminPanel = new AddAdminPanel(dbConn, null);
        
                // Add all panels to mainPanel if needed
                mainPanel.add(viewClientsPanel, "clients");
                mainPanel.add(viewAdminsPanel, "admins");
                mainPanel.add(viewCarsPanel, "cars");
                mainPanel.add(viewMessagesPanel, "messages");
                mainPanel.add(approvalPanel, "approvals");
        }

        /**
         * Switches the mainPanel to the given card
         */
        public void showPanel(String name) {
                java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
                if ("clients".equals(name)) {
                        viewClientsPanel.refreshData();
                } else if ("admins".equals(name)) {
                        viewAdminsPanel.refreshData();
                } else if ("cars".equals(name)) {
                        viewCarsPanel.refreshData();
                } else if ("approvals".equals(name)) {
                        viewMessagesPanel.refreshData();
                } else if ("approvals".equals(name)) {
                        // Refresh approval panel data when the card is shown
                        if (approvalPanel != null)
                                approvalPanel.refreshData();
                } else if ("dashboard".equals(name)) {
                        // Do not refresh dashboard automatically when switching back.
                        // The user requested manual refresh by clicking the Dashboard button.
                        if (jPanel14 != null) {
                                jPanel14.revalidate();
                                jPanel14.repaint();
                        }
                        if (jPanel15 != null) {
                                jPanel15.revalidate();
                                jPanel15.repaint();
                        }
                        if (jPanel16 != null) {
                                jPanel16.revalidate();
                                jPanel16.repaint();
                        }
                } else if ("addAdmin".equals(name)) {
                        // Clear the form when showing the add admin panel
                        addAdminPanel.clearForm();
                        // You could also refresh any data if needed
                }
                cl.show(mainPanel, name);
        }

}